<a href="https://colab.research.google.com/github/adiln135/Numpy/blob/main/Arrays_in_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# An ndarray (N-dimensional array) is the core, powerful data structure provided by the NumPy library
# 2D Array (Matrix / Grid)
import numpy as np
import time
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)  # Output: (2, 3) -> 2 rows, 3 columns
print(arr.ndim)   # Output: 2 (Number of dimensions)
print(arr.dtype)  # Output: int64 (Data type of the items)
print(arr.size)   # Output: 6 (Total number of elements)

(2, 3)
2
int64
6


# **Creating Arrays in NumPy**

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((2, 3)))  #To create an array of ones

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full((2,3), 7))

[[7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
import time

# Create 1 million items in a regular Python list and a NumPy array
size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

# Time how long it takes a Python list to add 2 to every item
start_time = time.time()
python_list = [x + 2 for x in python_list]
print(f"Python List took: {time.time() - start_time:.5f} seconds")

# Time how long it takes NumPy to do the exact same thing
start_time = time.time()
numpy_array = numpy_array + 2  # This is called Array Broadcasting!
print(f"NumPy Array took: {time.time() - start_time:.5f} seconds")


Python List took: 0.07632 seconds
NumPy Array took: 0.00529 seconds
