<a href="https://colab.research.google.com/github/adiln135/Numpy/blob/main/NumPy_Indexing_Slicing_%26_Strides.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

In [ ]:
print(arr[0,1])      # 20 (row 0, column 1)
print(arr[2,2])      # 90 (row 2, column 2)
print(arr[-1,-3])    # 70 (last row, 2nd last column)
print(arr[-3,-3])    # 10 (first row, first column)

20
90
70
10


In [ ]:
print(arr[0:2, 1:3 ])
 # 0:2 (First position): Selects the rows. It starts at index 0 and stops before index 2, giving you row 0 and row 1.
 # 1:3 (Second position): Selects the columns. It starts at index 1 and stops before index 3, giving you column 1 and column 2.

[[20 30]
 [50 60]]


In [ ]:
print(arr[::2, ::2])  # (row 0, row 2, row 4, etc.). (column 0, column 2, column 4, etc.).


[[10 30]
 [70 90]]


In [ ]:
slice_arr = arr[0, :2]
slice_arr[0] = 999
print(arr[0])

[999  20  30]
